# syntax=docker/dockerfile:1

FROM node:14 AS development

WORKDIR /usr/src/yobiservice

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

CMD ["npm", "run", "start:dev"]

# EXPOSE 3000
