version: '3.8'

services:
  room-man-booker-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    
    ports:
      - "3001:3000"

    command: npm run start:dev

    # restart: unless-stopped
    
    environment:
      NODE_ENV: development

    networks:
      - room-man-booker-network

    env_file:
      - .env.development


networks:
  room-man-booker-network:
    driver: bridge
